USE [master]
GO

/****** Object:  Database [OlympicsStage]    Script Date: 28/06/2015 17:06:31 ******/
CREATE DATABASE [OlympicsStage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Olimpiadas_Stage', FILENAME = N'D:\Documents\workspace\UNIVILLE\4ANO\SISPD\Integration Services\ETL Olimpiadas\Saidas\Bancos\Olimpiadas_Stage.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Olimpiadas_Stage_log', FILENAME = N'D:\Documents\workspace\UNIVILLE\4ANO\SISPD\Integration Services\ETL Olimpiadas\Saidas\Bancos\Olimpiadas_Stage_log.ldf' , SIZE = 5184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OlympicsStage] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OlympicsStage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OlympicsStage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OlympicsStage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OlympicsStage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OlympicsStage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OlympicsStage] SET ARITHABORT OFF 
GO

ALTER DATABASE [OlympicsStage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OlympicsStage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OlympicsStage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OlympicsStage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OlympicsStage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OlympicsStage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OlympicsStage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OlympicsStage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OlympicsStage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OlympicsStage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OlympicsStage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OlympicsStage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OlympicsStage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OlympicsStage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OlympicsStage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OlympicsStage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OlympicsStage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OlympicsStage] SET RECOVERY FULL 
GO

ALTER DATABASE [OlympicsStage] SET  MULTI_USER 
GO

ALTER DATABASE [OlympicsStage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OlympicsStage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OlympicsStage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OlympicsStage] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OlympicsStage] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OlympicsStage] SET  READ_WRITE 
GO


